# Local Benchmark Execution Configuration

# Core execution settings
benchmark:
  timeout: 300  # seconds per problem
  parallel_jobs: 1  # sequential execution (recommended for fair comparison)
  problem_sets:
    light_set: "problems/light_set"  # Only local problems supported
  
# Reporting configuration
reporting:
  formats: ["html", "json", "csv"]
  include_environment_info: true
  include_statistical_analysis: true

# Database configuration
database:
  path: "database/results.db"  # Local SQLite database

# Output configuration
output:
  reports_dir: "docs"  # Pre-built HTML files for GitHub Pages

# Legacy format support (for compatibility)
timeout: 300
parallel_jobs: 1
output_format: "json"