# Flat problem structure - each problem is a top-level entry
# Eliminates light_set in favor of real problems with test flags
problem_libraries:
  
  # Small-scale test problems from DIMACS/SDPLIB  
  nb:
    display_name: "ANTENNA NB (DIMACS)"
    file_path: "problems/DIMACS/data/ANTENNA/nb.mat.gz"
    file_type: "mat"
    problem_type: "SDP"
    library_name: "DIMACS"
    for_test_flag: true  # Small problem suitable for testing
    known_objective_value: -12.8  # Known optimal value for validation
    
  arch0:
    display_name: "ARCH0 (SDPLIB)"
    file_path: "problems/SDPLIB/data/arch0.dat-s"
    file_type: "dat-s" 
    problem_type: "SDP"
    library_name: "SDPLIB"
    for_test_flag: true  # Small problem suitable for testing
    known_objective_value: -5.6506  # Known optimal value
    
  # Larger production problems
  hinf12:
    display_name: "H-infinity Control 12 (DIMACS)"
    file_path: "problems/DIMACS/data/HINF/hinf12.mat.gz"
    file_type: "mat"
    problem_type: "SDP"
    library_name: "DIMACS"
    for_test_flag: false
    # known_objective_value: null  # Unknown - omit field
    
  control1:
    display_name: "Control Problem 1 (SDPLIB)"
    file_path: "problems/SDPLIB/data/control1.dat-s"
    file_type: "dat-s"
    problem_type: "SDP" 
    library_name: "SDPLIB"
    for_test_flag: false
    known_objective_value: 20.8  # Known optimal value
    
  gpp100:
    display_name: "Graph Partitioning 100 (SDPLIB)"
    file_path: "problems/SDPLIB/data/gpp100.dat-s"
    file_type: "dat-s"
    problem_type: "SDP"
    library_name: "SDPLIB" 
    for_test_flag: false
    # known_objective_value: null  # Unknown - omit field
    
  # Linear programming problems
  simple_lp_test:
    display_name: "Simple LP Test (Internal)"
    file_path: "problems/light_set/lp/simple_lp.mps"
    file_type: "mps"
    problem_type: "LP"
    library_name: "internal"
    for_test_flag: true  # Synthetic test problem
    known_objective_value: 5.0  # Known optimal value