site:
  title: "Optimization Solver Benchmark"
  author: "Naoki Ito"
  description: "Benchmarking optimization solvers with fair comparison"
  url: "https://napinoco.github.io/optimization-solver-benchmark"

github:
  username: "napinoco"
  repository: "optimization-solver-benchmark"